
.common_config: &common_config
  script:
    - cp .gitmodules-ci .gitmodules
    - git submodule sync
    - git submodule update --init
    - mkdir -p build && cd build
    - bash ../initialize_cmake.sh
    - make -j4
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
  after_script:
    - python3 extract_result.py build/Testing/Temporary/LastTest.log build/Testing/Temporary/LastTest.json
  artifacts:
    paths:
      - build/Testing/Temporary/*.log
      - build/Testing/Temporary/*.json
    expire_in: 1 year
    when: always
  cache:
    key: one-key-to-rule-them-all
    paths:
      - build/Testing/Temporary/LastTest.json


test_on_x86:
  <<: *common_config
  tags:
    - x86_64
  image: "debian:bullseye"
  before_script:
    - echo "deb http://mirrors.bfsu.edu.cn/debian bullseye main" > /etc/apt/sources.list &&
      echo "deb http://mirrors.bfsu.edu.cn/debian bullseye-updates main" >> /etc/apt/sources.list
    - apt-get update
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y make cmake g++ git llvm qemu-user g++-arm-linux-gnueabihf time python3-tabulate clang


test_on_arm:
  <<: *common_config
  tags:
    - armv7-a
