variables:
  RESULT_JSON_PATH: "build/Testing/Temporary/LastTest.json"

.common_config: &common_config
  image: "comp_judge:20.04"
  script:
    - cp .gitmodules-ci .gitmodules
    - git submodule sync
    - git submodule update --init
    - mkdir -p build && cd build
    - bash ../utils/initialize_cmake.sh
    - make -j4
    - bash ../utils/build_oneliner.sh
    - env CTEST_OUTPUT_ON_FAILURE=1 ctest
  after_script:
    - 'curl --header "PRIVATE-TOKEN: $CI_ARTIFACT_TOKEN" https://git.tsinghua.edu.cn/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/master/raw/${RESULT_JSON_PATH}?job=${CI_JOB_NAME} -o ${RESULT_JSON_PATH} || true'
    - python3 utils/extract_result.py build/Testing/Temporary/LastTest.log ${RESULT_JSON_PATH}
  artifacts:
    paths:
      - build/Testing/Temporary/*.log
      - build/*.S
      - build/*.bc
      - ${RESULT_JSON_PATH}
    expire_in: 1 year
    when: always


test_on_x86:
  <<: *common_config
  tags:
    - x86_64
    - docker


test_on_arm:
  <<: *common_config
  tags:
    - armv7-a
    - docker
