image: "debian:bullseye"

default:
  before_script:
    - echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian bullseye main" > /etc/apt/sources.list && \
      echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian bullseye-updates main" >> /etc/apt/sources.list
    - apt-get update
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y make cmake g++ git
    - cp .gitmodules-ci .gitmodules
    - git submodule sync
    - git submodule update --init

build_and_test:
  script:
    - mkdir -p build && cd build
    - cmake ..
    - make
    - make test
