variables:
  RESULT_JSON_PATH: "build/Testing/Temporary/LastTest.json"

.common_config: &common_config
  script:
    - cp .gitmodules-ci .gitmodules
    - git submodule sync
    - git submodule update --init
    - mkdir -p build && cd build
    - bash ../initialize_cmake.sh
    - make -j4
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
  after_script:
    - mkdir -p old_results && cd old_results
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" https://git.tsinghua.edu.cn/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=${CI_JOB_NAME} -o old_results.zip || true'
    - unzip ../old_results.zip || true
    - mv ${RESULT_JSON_PATH} ../${RESULT_JSON_PATH} || true
    - cd ..
    - python3 extract_result.py build/Testing/Temporary/LastTest.log ${RESULT_JSON_PATH}
  artifacts:
    paths:
      - build/Testing/Temporary/*.log
      - ${RESULT_JSON_PATH}
    expire_in: 1 year
    when: always


test_on_x86:
  <<: *common_config
  tags:
    - x86_64
  image: "debian:bullseye"
  before_script:
    - echo "deb http://mirrors.bfsu.edu.cn/debian bullseye main" > /etc/apt/sources.list &&
      echo "deb http://mirrors.bfsu.edu.cn/debian bullseye-updates main" >> /etc/apt/sources.list
    - apt-get update
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y make cmake g++ git llvm qemu-user g++-arm-linux-gnueabihf time python3-tabulate clang unzip curl


test_on_arm:
  <<: *common_config
  tags:
    - armv7-a
