variables:
  RESULT_JSON_PATH: "build/Testing/Temporary/LastTest.json"

.common_config: &common_config
  script:
    - cp .gitmodules-ci .gitmodules
    - git submodule sync
    - git submodule update --init
    - mkdir -p build && cd build
    - bash ../initialize_cmake.sh
    - make -j4
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
  after_script:
    - 'curl --header "PRIVATE-TOKEN: $CI_ARTIFACT_TOKEN" https://git.tsinghua.edu.cn/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/master/raw/${RESULT_JSON_PATH}?job=${CI_JOB_NAME} -o ${RESULT_JSON_PATH} || true'
    - python3 extract_result.py build/Testing/Temporary/LastTest.log ${RESULT_JSON_PATH}
  artifacts:
    paths:
      - build/Testing/Temporary/*.log
      - build/*.S
      - build/*.bc
      - ${RESULT_JSON_PATH}
    expire_in: 1 year
    when: always


test_on_x86:
  <<: *common_config
  tags:
    - x86_64
    - docker
  image: "ubuntu:20.04"
  before_script:
    - echo "deb http://mirrors.bfsu.edu.cn/ubuntu/ focal main restricted universe multiverse" > /etc/apt/sources.list &&
      echo "deb http://mirrors.bfsu.edu.cn/ubuntu/ focal-updates main restricted universe multiverse" >> /etc/apt/sources.list
    - apt-get update
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake git llvm qemu-user g++-arm-linux-gnueabihf time python3-tabulate clang unzip curl


test_on_arm:
  <<: *common_config
  tags:
    - armv7-a
    - docker
  image: "comp_judge:20.04"
