image: "debian:bullseye"

default:
  before_script:
    - echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian bullseye main" > /etc/apt/sources.list &&
      echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian bullseye-updates main" >> /etc/apt/sources.list
    - apt-get update
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y make cmake g++ git llvm qemu-user g++-arm-linux-gnueabihf
    - cp .gitmodules-ci .gitmodules
    - git submodule sync
    - git submodule update --init

build_and_test:
  script:
    - mkdir -p build && cd build
    - cmake ..
    - make
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
    - python3 ../extract_result.py Testing/Temporary/LastTest.log
  artifacts:
    paths:
      - build/Testing/Temporary/*.log
    expire_in: 1 year
    when: always
