name: Build and Test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        container: jiegec/comp_judge:20.04
        steps:
            - uses: actions/checkout@v2
            - uses: textbook/git-checkout-submodule-action@master
            - run: bash utils/run_test.sh
              env:
                CI_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
            - run: python3 utils/extract_result.py build/Testing/Temporary/LastTest.log build/Testing/Temporary/LastTest.json
            - uses: actions/upload-artifact@v2
              with:
                name: run-result
                path: |
                  build/Testing/Temporary/*.log
                  build/*.S
                  build/*.bc
                  build/Testing/Temporary/LastTest.log build/Testing/Temporary/LastTest.json
