name: Build and Test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        container: jiegec/comp_judge:20.04
        steps:
            - uses: actions/checkout@v2
            - run: bash utils/run_test.sh
            - run: python3 utils/extract_result.py build/Testing/Temporary/LastTest.log build/Testing/Temporary/LastTest.json
            - uses: actions/upload-artifact@v2
              with:
                name: run-result
                path: |
                  build/Testing/Temporary/*.log
                  build/*.S
                  build/*.bc
                  build/Testing/Temporary/LastTest.log build/Testing/Temporary/LastTest.json
                  